project: 
  type: website
  output-dir: docs

website: 
  sidebar:
    - title: "Tableau de Bord sur R"
      style: "docked"
      search: true
      background: light
      contents: 
        - href: index.qmd
        - section: "Base de R"
          contents: 
            - href: Intro.qmd
            - href: logical.qmd
        - section: "Manipulation"
          contents:
          - href: import.qmd
          - href: creationselect.qmd
          - href: stringmanip.qmd
          - href: dplyrexercice.qmd
        - section: "Visualisation"
          contents: 
          - href: vizggplot.qmd
          - href: exoggplot.qmd
          - href: vizplotly.qmd
          - href: exoplotly.qmd
          - href: vizhighcharter.qmd
        - section: "Shiny Application"
          contents: 
          - href: introdtoshiny.qmd
          
          
format:
 html: 
  theme: cosmo
  css: styles.css
  toc: true
  fig-width: 8
  fig-height: 6
  html-math-method: katex
  code-fold: false

